files = Split("""
	binreloc.c  editor.c  exit.c
	init.c      kuri2d.c  logic.c
	main.c      menu.c    SDL_shish.c
	""")
libs  = ['SDLmain', 'SDL_ttf', 'SDL_image', 'png', 'SDL']
flags = [
	'-I/usr/include/SDL/', 
	'-DVERSION=\\"0.9.0\\"', '-DENABLE_BINRELOC=1', 
	'-Wall', '-ggdb']

opts = Options('custom.py')
opts.Add(PathOption('PREFIX', 'Install prefix', '/usr/local'))
env = Environment(options = opts, LIBS=libs, CCFLAGS=flags)

kuri2d = env.Program('kuri2d', files)

env.Install('$PREFIX', kuri2d)
env.Alias('install', '$PREFIX')

